apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mcs5xdfai-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:25d25dc4404abd76fb6c2dffa86a070acc55ac7c@sha256:d483603f710f58c8ad9fd2dd367767b98d41bd25e6a4e0f335b988d334cdd1d2
          name: container-image
