apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mcs5xdfai-java-springboot
  janus-idp.io/tekton: mcs5xdfai-java-springboot
  backstage.io/kubernetes-id: mcs5xdfai-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mcs5xdfai-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
